import joblib
import pandas as pd

from src.config import PROCESSED_DIR


def load_splits():
    """
    Load preprocessed train/val splits generated by run_full_pipeline().
    """
    splits_dir = PROCESSED_DIR / "splits"

    X_train = joblib.load(splits_dir / "X_train.joblib")
    y_train = joblib.load(splits_dir / "y_train.joblib")
    X_val = joblib.load(splits_dir / "X_val.joblib")
    y_val = joblib.load(splits_dir / "y_val.joblib")

    if not isinstance(X_train, pd.DataFrame):
        X_train = pd.DataFrame(X_train)
    if not isinstance(X_val, pd.DataFrame):
        X_val = pd.DataFrame(X_val)

    if not isinstance(y_train, pd.Series):
        y_train = pd.Series(y_train, name="isFraud")
    if not isinstance(y_val, pd.Series):
        y_val = pd.Series(y_val, name="isFraud")

    return X_train, y_train, X_val, y_val
